"""Criar tabelas iniciais

Revision ID: 63b90855f98e
Revises: 
Create Date: 2025-10-27 11:44:47.840875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63b90855f98e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cliente', 'cpf',
               existing_type=sa.CHAR(length=11),
               type_=sa.String(length=11),
               existing_nullable=False)
    op.alter_column('endereco', 'estado',
               existing_type=sa.CHAR(length=2),
               type_=sa.String(length=2),
               existing_nullable=False)
    op.alter_column('endereco', 'cep',
               existing_type=sa.CHAR(length=9),
               type_=sa.String(length=9),
               existing_nullable=False)
    op.drop_constraint(op.f('parcela_id_financeiro_numero_parcela_key'), 'parcela', type_='unique')
    op.create_unique_constraint('uq_financeiro_numero_parcela', 'parcela', ['id_financeiro', 'numero_parcela'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_financeiro_numero_parcela', 'parcela', type_='unique')
    op.create_unique_constraint(op.f('parcela_id_financeiro_numero_parcela_key'), 'parcela', ['id_financeiro', 'numero_parcela'], postgresql_nulls_not_distinct=False)
    op.alter_column('endereco', 'cep',
               existing_type=sa.String(length=9),
               type_=sa.CHAR(length=9),
               existing_nullable=False)
    op.alter_column('endereco', 'estado',
               existing_type=sa.String(length=2),
               type_=sa.CHAR(length=2),
               existing_nullable=False)
    op.alter_column('cliente', 'cpf',
               existing_type=sa.String(length=11),
               type_=sa.CHAR(length=11),
               existing_nullable=False)
    # ### end Alembic commands ###
